# Generated by Django 4.2.4 on 2023-08-22 16:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='info',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
